### ISSUE TITLE
Bug make application setp error

### ISSUE THREAD

**Issue by guoziqin** [Activiti/activiti-cloud-examples#120] opened 2020-05-11 03:29 UTC
The docker-compose lacks activtiti-cloud-audit and activtiti-cloud-captures-graphql
So executing make application will report an error and how do you add it? @jesty @mteodori @salaboy @magemello @wabson @

**Comment by guoziqin** [comment] 2020-05-11 03:32
Pull the code to deploy and you will see the above error

**Comment by mteodori** [comment] 2020-05-11 18:08
duplicate of #117

**Closed as completed by mteodori** 2020-05-11 18:08 UTC
Labels: bug, duplicate
